using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using static Core.StaticMethod.Method.Utils.EnumUtilsMet;

namespace Core.DefaultData.DataLibrary {
    /// <summary>
    /// 默认姓名配置枚举类
    /// </summary>
    public enum DefaultNameEnum{
        /// <summary>
        /// 程序本身命名
        /// </summary>
        [EnumDescription("CharsToolset")] PROGRAM_NAME,
        /// <summary>
        /// 启动窗体的默认命名
        /// </summary>
        [EnumDescription("RootDisplayForm")] ROOT_FORM_NAME,
        /// <summary>
        /// 查找和替换窗口的默认命名
        /// </summary>
        [EnumDescription("FindAndReplace")] FIND_REPLACE_FORM,
        /// <summary>
        /// 分列窗口的默认命名
        /// </summary>
        [EnumDescription("SplitCharsForm")] SPLIT_CHARS_FORM,
        /// <summary>
        /// 添加字符窗体的默认密码
        /// </summary>
        [EnumDescription("AddCharsForm")] ADD_CHARS_FORM,
        /// <summary>
        /// 字段转JAVA实体类的默认命名
        /// </summary>
        [EnumDescription("FieldToJavaEntity")] FIELD_TO_JAVA_ENTITY,
        /// <summary>
        /// 默认文本框右键菜单命名
        /// </summary>
        [EnumDescription("textRightMenu")] TEXT_RIGHT_MENU,
        /// <summary>
        /// tag中的删除按钮的key
        /// </summary>
        [EnumDescription("delbut")] DEF_BUTTON_TAG_KEY,
        /// <summary>
        /// 程序主容器命名
        /// </summary>
        [EnumDescription("mainContainer")] MAIN_CONTAINER,
        /// <summary>
        /// 状态栏默认命名
        /// </summary>
        [EnumDescription("statusStrip")] TOOL_START,
        /// <summary>
        /// 顶部菜单默认命名
        /// </summary>
        [EnumDescription("topMenuStrip")] TOP_MENU,
        /// <summary>
        /// 文本框的默认命名
        /// </summary>
        [EnumDescription("mainTextBox")] TEXTBOX_NAME_DEF,
        /// <summary>
        /// 默认标签容器命名
        /// </summary>
        [EnumDescription("mainTabControl")] TAB_CONTENT,
        /// <summary>
        /// 调整大小角标的命名
        /// </summary>
        [EnumDescription("sizeSubscript")] SIZE_SUBSCRIPT,
        /// <summary>
        /// 默认表格右键菜单命名
        /// </summary>
        [EnumDescription("dataViewRightMenu")] DATA_VIEW_RIGHT_MENU,
        /// <summary>
        /// 默认添加标签按钮命名
        /// </summary>
        [EnumDescription("mainAddPageButton")] ADD_PAGE_BUTTON,
        /// 默认删除标签按钮命名
        /// </summary>
        [EnumDescription("delPageButton")] DEL_PAGE_BUTTON
    }
}
